# Generated by Django 4.2 on 2023-04-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rock',
            name='description',
            field=models.CharField(default='rock', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rock',
            name='name',
            field=models.CharField(default='rock', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rock',
            name='type',
            field=models.CharField(default='rock', max_length=100),
            preserve_default=False,
        ),
    ]
