# Generated by Django 4.2 on 2023-04-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_observation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mineral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='rock',
            name='minerals',
            field=models.ManyToManyField(to='main_app.mineral'),
        ),
    ]
